# Generates custom.css — the GENGHIS themes for Open WebUI.
# Open WebUI paints its dark UI from a --color-gray-50..950 ramp (oklch). A theme = that ramp re-tinted AND re-spaced
# for hierarchy (sidebar darkest -> canvas -> panels/composer lifted, borders visible), plus ONE accent applied only to
# interactive things (send, the model name, the active chat, focus, links, the mic) and a second, quieter note for
# the "Thought" line. Text steps stay nearly neutral so contrast never depends on the tint.
import sys, os
out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "custom.css")

# Lightness per ramp step. Stock is flat (900=20, 850=27, 950=16); ours opens the gaps so surfaces read as layers:
# 950 sidebar 13 · 900 canvas 19 · 850 panels/composer/user-bubble 28 · 800 hover/borders 35 · 700 strong borders 44.
L = {50: 98, 100: 94, 200: 90, 300: 83, 400: 74, 500: 66, 600: 52, 700: 44, 800: 35, 850: 28, 900: 19, 950: 13}
# A MID-TONE ramp for the daylight-studio themes (canvas ~30%, panels ~37%): calmer than near-black, still dark mode.
L_MID = {50: 98, 100: 95, 200: 92, 300: 87, 400: 79, 500: 71, 600: 58, 700: 50, 800: 43, 850: 37, 900: 30, 950: 22}

# key -> (label, hue, chroma at the dark/surface end, chroma at the light/text end, accent, accent-2, note)
THEMES = {
    "khan":      ("Khan",         85,  0.020, 0.004, "oklch(83% 0.17 85)",  "oklch(72% 0.13 70)",  "gold on black — the house colours"),
    "blackwell": ("Blackwell",    150, 0.010, 0.002, "oklch(84% 0.23 132)", "oklch(72% 0.10 250)", "graphite with a lime edge"),
    "rizen":     ("Rizen' Up",    310, 0.035, 0.006, "oklch(66% 0.26 18)",  "oklch(78% 0.12 340)", "plum surfaces, signal-red controls"),
    "arc":       ("Arc Light",    220, 0.060, 0.010, "oklch(84% 0.15 190)", "oklch(74% 0.11 235)", "deep teal with cyan"),
    "steppe":    ("Steppe Night", 278, 0.048, 0.010, "oklch(84% 0.11 285)", "oklch(80% 0.13 320)", "slate blue with lavender"),
    "overclock": ("Overclock",    5,   0.085, 0.012, "oklch(93% 0.20 100)", "oklch(86% 0.15 195)", "crimson, electric yellow, cyan"),
    # mid-tone (L_MID ramp)
    "tundra":    ("Tundra",       235, 0.040, 0.008, "oklch(76% 0.13 235)", "oklch(86% 0.16 90)",  "slate blue-gray, steel-blue controls, a gold note"),
    "foundry":   ("Foundry",      240, 0.012, 0.003, "oklch(74% 0.15 235)", "oklch(66% 0.18 25)",  "mid graphite, sky-blue controls, a warm-red note"),
}
MID = {"tundra", "foundry"}
# 60/30/10 (cinema): a COMPLEMENTARY hue for the 30% surfaces (850/800/700 = panels, composer, bubbles, borders) so
# hierarchy comes from temperature as well as lightness; one accent on the 10%. key -> (hue2, chroma2)
PANEL_HUE = {"ordu": (238, 0.055)}
THEMES["ordu"] = ("Ordu", 60, 0.018, 0.006, "oklch(78% 0.15 60)", "oklch(72% 0.10 60)",
                  "60/30/10: warm charcoal felt, the cool blue steppe through the door, one ember")

css = ["/* GENGHIS themes for Open WebUI — generated by gen_themes.py. Pick one at /static/genghis-themes.html",
       "   (sets localStorage.genghisTheme; /static/loader.js applies data-genghis-theme on <html>). */", ""]
for key, (label, hue, c_dark, c_light, acc, acc2, note) in THEMES.items():
    sel = f'html[data-genghis-theme="{key}"]'
    css.append(f"/* {label} — {note} */")
    css.append(f"{sel} {{")
    ramp = L_MID if key in MID else L
    for step, l in ramp.items():
        t = (98 - l) / (98 - min(ramp.values()))      # 0 at the text end, 1 at the darkest surface
        c = c_light + (c_dark - c_light) * (t ** 1.4)  # tint lives in the surfaces, barely in the text
        h = hue
        if key in PANEL_HUE and step in (700, 800, 850):    # the 30%: complementary temperature
            h, c = PANEL_HUE[key]
        css.append(f"  --color-gray-{step}: oklch({l}% {c:.3f} {h});")
    css.append(f"  --genghis-accent: {acc};")
    css.append(f"  --genghis-accent-2: {acc2};")
    css.append("}")
    css.append("")

css.append(r"""/* ---- shared rules: hierarchy + one accent on interactive elements (real selectors from Open WebUI v0.11) ---- */
/* The composer is a PANEL, not a ghost: a solid lifted surface, a visible border, the accent when focused. */
html[data-genghis-theme].dark #message-input-container {
  background-color: var(--color-gray-850) !important;
  border: 1px solid var(--color-gray-700) !important;
  outline: 1px solid color-mix(in oklch, var(--color-gray-700) 60%, transparent); outline-offset: -2px;
  box-shadow: 0 8px 30px -12px rgba(0,0,0,.6);
}
html[data-genghis-theme].dark #message-input-container:focus-within {
  border-color: color-mix(in oklch, var(--genghis-accent) 70%, var(--color-gray-700)) !important;
  box-shadow: 0 0 0 3px color-mix(in oklch, var(--genghis-accent) 22%, transparent), 0 8px 30px -12px rgba(0,0,0,.6);
}
/* Send = the accent (stock is plain white). Mic/record too. */
html[data-genghis-theme].dark #send-message-button { background-color: var(--genghis-accent) !important; color: oklch(15% 0 0) !important; }
html[data-genghis-theme].dark #send-message-button:hover { filter: brightness(1.12); }
html[data-genghis-theme].dark #confirm-recording-button { background-color: var(--genghis-accent) !important; color: oklch(15% 0 0) !important; }
/* The model's name is the one label that should carry the accent. */
html[data-genghis-theme].dark #model-selector-model-button > div { color: var(--genghis-accent) !important; }
html[data-genghis-theme].dark #model-selector-model-button:hover > div { filter: brightness(1.12); }
/* Sidebar: darkest layer; the ACTIVE chat gets an accent bar + tint. */
html[data-genghis-theme].dark #sidebar { border-right: 1px solid var(--color-gray-800); }
html[data-genghis-theme].dark #sidebar-chat-item.bg-gray-900, html[data-genghis-theme].dark #sidebar-chat-item[class*="dark:bg-gray-900"] {
  background: color-mix(in oklch, var(--genghis-accent) 14%, var(--color-gray-900)) !important;
  box-shadow: inset 3px 0 0 var(--genghis-accent);
}
html[data-genghis-theme].dark #sidebar-chat-item:hover { background: color-mix(in oklch, var(--genghis-accent) 8%, var(--color-gray-900)); }
/* User bubbles are panels; assistant text sits on the canvas — the pairing that gives a chat its rhythm. */
html[data-genghis-theme].dark .chat-user .rounded-3xl, html[data-genghis-theme].dark .chat-user [class*="bg-gray-850"] {
  background-color: var(--color-gray-850) !important; border: 1px solid var(--color-gray-800);
}
/* "Thought for N seconds" and the tool-call rows: the quieter second accent. */
html[data-genghis-theme].dark details > summary, html[data-genghis-theme].dark .chat-assistant summary { color: var(--genghis-accent-2) !important; }
/* Links in answers, selection, focus rings. */
html[data-genghis-theme] ::selection { background: color-mix(in oklch, var(--genghis-accent) 40%, transparent); }
html[data-genghis-theme].dark .prose a, html[data-genghis-theme].dark .markdown-prose a, html[data-genghis-theme].dark .chat-assistant a { color: var(--genghis-accent) !important; }
html[data-genghis-theme] *:focus-visible { outline: 2px solid var(--genghis-accent) !important; outline-offset: 2px; }
/* ...except inside the composer: its own border already shows focus; a second rectangle in a rounded panel is noise */
html[data-genghis-theme] #message-input-container *:focus-visible, html[data-genghis-theme] #chat-input:focus, html[data-genghis-theme] #chat-input:focus-visible { outline: none !important; box-shadow: none !important; }
/* Stock blue/indigo utility colours (toggles, badges) follow the accent so no theme has a stray blue. */
html[data-genghis-theme].dark .bg-blue-500, html[data-genghis-theme].dark .bg-blue-600, html[data-genghis-theme].dark .bg-indigo-500 { background-color: var(--genghis-accent) !important; }
html[data-genghis-theme].dark .text-blue-500, html[data-genghis-theme].dark .text-blue-600, html[data-genghis-theme].dark .text-blue-400 { color: var(--genghis-accent) !important; }
html[data-genghis-theme].dark .border-blue-500 { border-color: var(--genghis-accent) !important; }
/* Code blocks: a distinct, darker inset so they read as code, not as another panel. */
html[data-genghis-theme].dark pre, html[data-genghis-theme].dark .cm-editor { background-color: var(--color-gray-950) !important; border: 1px solid var(--color-gray-800); }
/* Buttons that are white-on-dark in stock become the accent (primary actions) */
html[data-genghis-theme].dark button.bg-white.text-black, html[data-genghis-theme].dark button[class*="dark:bg-white"] { background-color: var(--genghis-accent) !important; color: oklch(15% 0 0) !important; }
""")
open(out, "w", encoding="utf-8", newline="\n").write("\n".join(css))
print("wrote", out, len("\n".join(css)), "bytes;", len(THEMES), "themes")
